// Generated by _tools/sync-photos.py. Set "kind" to "places" (city or
// architecture) or "cosplay"; the script keeps it. The intro and the
// gallery always open with a "places" photo.
window.PHOTOS = [
    {"id": "20250524-193709", "kind": "places", "w": 2000, "h": 1500, "src": "b268b59f5cd0"},
    {"id": "20250525-183410", "kind": "places", "w": 2000, "h": 1506, "src": "28ffb24a850c"},
    {"id": "20250606-144127", "kind": "places", "w": 2000, "h": 1500, "src": "3e022552c00f"},
    {"id": "20251123-163943", "kind": "cosplay", "w": 1506, "h": 2000, "src": "652782e19649"},
    {"id": "20251221-185902", "kind": "cosplay", "w": 2000, "h": 1500, "src": "32fb6cf51049"},
    {"id": "20260412-171113", "kind": "cosplay", "w": 1506, "h": 2000, "src": "106d6885bd7a"},
    {"id": "20260418-174819", "kind": "cosplay", "w": 1506, "h": 2000, "src": "fef4837206b3"},
    {"id": "20260419-165525", "kind": "cosplay", "w": 2000, "h": 1506, "src": "6c96cb2b5f0b"},
    {"id": "20260426-190045", "kind": "cosplay", "w": 2000, "h": 1506, "src": "58a18e1ff1be"},
    {"id": "20260531-182758", "kind": "cosplay", "w": 1506, "h": 2000, "src": "2251ea95c6c1"},
    {"id": "20260531-191802", "kind": "cosplay", "w": 2000, "h": 1506, "src": "23953ecab149"},
    {"id": "20260614-164807", "kind": "cosplay", "w": 2000, "h": 1506, "src": "ebcee14dd8f7"},
    {"id": "20260614-182300", "kind": "cosplay", "w": 2000, "h": 1506, "src": "c6ed00937304"},
    {"id": "20260614-183647", "kind": "cosplay", "w": 2000, "h": 1506, "src": "0e714bdcff49"},
    {"id": "20260614-194950", "kind": "cosplay", "w": 2000, "h": 1506, "src": "eb1fbe0388ae"},
    {"id": "20260719-173649", "kind": "cosplay", "w": 1506, "h": 2000, "src": "ad44be7354a7"},
    {"id": "20260719-175743", "kind": "cosplay", "w": 2000, "h": 1506, "src": "3b6605e25a53"},
    {"id": "20260719-180713", "kind": "cosplay", "w": 1506, "h": 2000, "src": "1ed6f84894f5"},
    {"id": "20260726-164854", "kind": "cosplay", "w": 1506, "h": 2000, "src": "8ea5d28c5a4d"},
    {"id": "20260726-184257", "kind": "cosplay", "w": 2000, "h": 1506, "src": "a70deb95c490"},
    {"id": "20260809-174909", "kind": "cosplay", "w": 2000, "h": 1506, "src": "233b950cb6e3"},
    {"id": "20260823-153649", "kind": "cosplay", "w": 2000, "h": 1506, "src": "1a61884ea6d1"},
    {"id": "20260823-190636", "kind": "cosplay", "w": 2000, "h": 1506, "src": "0335b5547396"},
    {"id": "20260823-204340", "kind": "cosplay", "w": 2000, "h": 1506, "src": "12d0d7447464"},
    {"id": "20260830-181056", "kind": "cosplay", "w": 1506, "h": 2000, "src": "1009f8199de6"},
    {"id": "20260831-195753", "kind": "places", "w": 1676, "h": 2000, "src": "aadbd7b4541c"},
    {"id": "20260901-192204", "kind": "places", "w": 2000, "h": 1502, "src": "894749ffcce1"},
    {"id": "20260913-174354", "kind": "cosplay", "w": 1506, "h": 2000, "src": "a3b3c1d8d728"}
];
