// Generated by _tools/sync-photos.py. Set "kind" to "places" (city or
// architecture) or "cosplay", and "alt" to a short description for screen
// readers; the script keeps both. The intro and the gallery always open
// with a "places" photo.
window.PHOTOS = [
    {"id": "0335b5547396", "kind": "cosplay", "alt": "A cosplayer with cat-ear headphones aiming a camera with a big telephoto lens and flash", "w": 2000, "h": 1506, "src": "0335b5547396"},
    {"id": "0e714bdcff49", "kind": "cosplay", "alt": "A cosplayer with silver pigtails and pointed ears in a pale teal dress, sitting on the grass", "w": 2000, "h": 1506, "src": "0e714bdcff49"},
    {"id": "1009f8199de6", "kind": "cosplay", "alt": "A cosplayer with light blue hair and a navy bow in a sailor-style dress, looking back", "w": 1506, "h": 2000, "src": "1009f8199de6"},
    {"id": "106d6885bd7a", "kind": "cosplay", "alt": "A cosplayer in a pink wig and white sun hat sipping an iced drink against a warm evening sky", "w": 1506, "h": 2000, "src": "106d6885bd7a"},
    {"id": "12d0d7447464", "kind": "cosplay", "alt": "A cosplayer in a white and lilac gown under a black umbrella on a wet street at night", "w": 2000, "h": 1506, "src": "12d0d7447464"},
    {"id": "1a61884ea6d1", "kind": "cosplay", "alt": "A cosplayer with short burgundy hair and a black choker under a clear umbrella", "w": 2000, "h": 1506, "src": "1a61884ea6d1"},
    {"id": "1ed6f84894f5", "kind": "cosplay", "alt": "A cosplayer with purple hair in a white shirt and black pinafore, hugging a notebook", "w": 1506, "h": 2000, "src": "1ed6f84894f5"},
    {"id": "2251ea95c6c1", "kind": "cosplay", "alt": "A cosplayer with pink hair and bunny ears in a white shirt and red bow, holding a phone", "w": 1506, "h": 2000, "src": "2251ea95c6c1"},
    {"id": "233b950cb6e3", "kind": "cosplay", "alt": "Two cosplayers at a railing, one with long dark hair, one in a black and white maid-style outfit", "w": 2000, "h": 1506, "src": "233b950cb6e3"},
    {"id": "23953ecab149", "kind": "cosplay", "alt": "Two cosplayers back to back at night, one with long blue hair, one with red hair holding a fan", "w": 2000, "h": 1506, "src": "23953ecab149"},
    {"id": "28ffb24a850c", "kind": "places", "alt": "Tall apartment towers and a glass office building with a KINTEX sign against a clear blue sky", "w": 2000, "h": 1506, "src": "28ffb24a850c"},
    {"id": "32fb6cf51049", "kind": "cosplay", "alt": "A cosplayer with spiky red hair posing in a forest at dusk with a huge scythe-like weapon", "w": 2000, "h": 1500, "src": "32fb6cf51049"},
    {"id": "3b6605e25a53", "kind": "cosplay", "alt": "Two cosplayers with purple hair lying on the grass, one reading a small blue book", "w": 2000, "h": 1506, "src": "3b6605e25a53"},
    {"id": "3e022552c00f", "kind": "places", "alt": "A sunlit dirt path through a tunnel of green trees", "w": 2000, "h": 1500, "src": "3e022552c00f"},
    {"id": "58a18e1ff1be", "kind": "cosplay", "alt": "A cosplayer with black and red hair in a white and blue outfit with a large white wing", "w": 2000, "h": 1506, "src": "58a18e1ff1be"},
    {"id": "652782e19649", "kind": "cosplay", "alt": "A cosplayer with a short blue bob in a white off-shoulder dress, holding up a folding fan", "w": 1506, "h": 2000, "src": "652782e19649"},
    {"id": "6c96cb2b5f0b", "kind": "cosplay", "alt": "A cosplayer with silver hair in a red and black dress, holding a red paper umbrella", "w": 2000, "h": 1506, "src": "6c96cb2b5f0b"},
    {"id": "894749ffcce1", "kind": "places", "alt": "A city at night seen from high above, with a river and lit-up towers", "w": 2000, "h": 1502, "src": "894749ffcce1"},
    {"id": "8ea5d28c5a4d", "kind": "cosplay", "alt": "A cosplayer with long dark hair in a blue dress, black gloves and a blue rose headpiece", "w": 1506, "h": 2000, "src": "8ea5d28c5a4d"},
    {"id": "a3b3c1d8d728", "kind": "cosplay", "alt": "A cosplayer with long dark blue hair in a black and gold coat, adjusting a black glove", "w": 1506, "h": 2000, "src": "a3b3c1d8d728"},
    {"id": "a70deb95c490", "kind": "cosplay", "alt": "A cosplayer with long blond pigtails, a white beret and pink arm warmers, holding a phone", "w": 2000, "h": 1506, "src": "a70deb95c490"},
    {"id": "aadbd7b4541c", "kind": "places", "alt": "Looking up at a curved glass skyscraper lit up at night", "w": 1676, "h": 2000, "src": "aadbd7b4541c"},
    {"id": "ad44be7354a7", "kind": "cosplay", "alt": "A blond cosplayer in a pink and blue jacket holding a red rose among tall grass", "w": 1506, "h": 2000, "src": "ad44be7354a7"},
    {"id": "b268b59f5cd0", "kind": "places", "alt": "Seoul Station's glass front and sign at dusk, under a pink and purple sky", "w": 2000, "h": 1500, "src": "b268b59f5cd0"},
    {"id": "c6ed00937304", "kind": "cosplay", "alt": "Silhouette of a cosplayer with a long braid holding red spider lilies at sunset", "w": 2000, "h": 1506, "src": "c6ed00937304"},
    {"id": "eb1fbe0388ae", "kind": "cosplay", "alt": "A cosplayer in a green and white uniform and cap, reaching both hands toward the camera", "w": 2000, "h": 1506, "src": "eb1fbe0388ae"},
    {"id": "ebcee14dd8f7", "kind": "cosplay", "alt": "A cosplayer with blue hair in a white dress, seen from behind, walking through tall grass", "w": 2000, "h": 1506, "src": "ebcee14dd8f7"},
    {"id": "fef4837206b3", "kind": "cosplay", "alt": "A cosplayer with long dark purple hair under a crown of pink cherry blossoms, in profile", "w": 1506, "h": 2000, "src": "fef4837206b3"}
];
